version: "3"
services:
    eclipse-mosquitto:
        restart: unless-stopped
        ports:
          - 1883:1883
          - 9001:9001
        volumes:
            - /mosquitto/data
            - /mosquitto/log
            - ./conf:/mosquitto/config
        image: docker.io/eclipse-mosquitto
